title: "Advanced Scientific Computing Methods for Modern Research"
short_title: "Scientific Computing Methods"

authors:
  - name: "Dr. John A. Smith"
    affiliation: "Department of Computer Science, University of Technology"
    email: "j.smith@university.edu"
    corresponding: true
    orcid: "0000-0002-1234-5678"
  
  - name: "Dr. Mary B. Johnson"
    affiliation: "Institute for Computational Sciences, Tech University"
    email: "m.johnson@tech.edu"
    corresponding: false
    orcid: "0000-0003-2345-6789"

affiliations:
  - name: "University of Technology"
    address: "123 Science Drive, Tech City, TC 12345"
    department: "Department of Computer Science"
  
  - name: "Tech University"
    address: "456 Research Avenue, Innovation City, IC 67890"
    department: "Institute for Computational Sciences"

abstract: |
  This paper presents novel approaches to scientific computing that leverage
  modern computational techniques. We demonstrate significant improvements
  in performance and accuracy across various scientific domains.

keywords:
  - "scientific computing"
  - "computational methods"
  - "high-performance computing"
  - "numerical algorithms"

date: "2023-12-01"
journal: "Journal of Computational Science"

acknowledgments: |
  We thank the reviewers for their valuable feedback and the computing
  facility for providing computational resources.

funding: |
  This work was supported by the National Science Foundation under
  grant number NSF-12345.

conflicts: "The authors declare no conflicts of interest."

data_availability: |
  The data supporting this study are available from the corresponding
  author upon reasonable request.

bibliography:
  style: "numeric"
  file: "03_REFERENCES.bib"

format:
  paper_size: "a4"
  margin: "2.5cm"
  line_spacing: 1.5
  font_size: "11pt"
  columns: 1

preprint:
  server: "arxiv"
  subject: "cs.SC"
  license: "CC BY"