name: 'Artifact Management'
description: 'Standardized artifact upload and download patterns'
inputs:
  action:
    description: 'Action to perform: upload, download, or upload-test-results'
    required: true
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'File paths to upload (for upload) or download path (for download)'
    required: false
    default: ''
  retention-days:
    description: 'Artifact retention days'
    required: false
    default: '30'
  merge-multiple:
    description: 'Merge multiple artifacts when downloading'
    required: false
    default: 'false'
  fail-on-error:
    description: 'Fail the workflow if artifact operation fails'
    required: false
    default: 'true'
  matrix-os:
    description: 'OS from matrix for test results naming'
    required: false
    default: ''
  matrix-python:
    description: 'Python version from matrix for test results naming'
    required: false
    default: ''

outputs:
  artifact-id:
    description: 'Created artifact ID'
    value: ${{ steps.upload.outputs.artifact-id }}
  download-path:
    description: 'Download path for artifacts'
    value: ${{ steps.download.outputs.download-path }}

runs:
  using: 'composite'
  steps:
    - name: Upload artifact
      if: inputs.action == 'upload'
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        retention-days: ${{ inputs.retention-days }}

    - name: Upload test results
      if: inputs.action == 'upload-test-results'
      id: upload-test
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ inputs.matrix-os }}-${{ inputs.matrix-python }}
        path: |
          pytest-results.xml
          htmlcov/
          coverage.xml
        retention-days: ${{ inputs.retention-days }}

    - name: Download artifact
      if: inputs.action == 'download'
      id: download
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path || inputs.name }}
        merge-multiple: ${{ inputs.merge-multiple }}

    - name: Download all artifacts
      if: inputs.action == 'download-all'
      id: download-all
      uses: actions/download-artifact@v4
      with:
        merge-multiple: ${{ inputs.merge-multiple }}
        path: ${{ inputs.path || 'artifacts/' }}

    - name: List downloaded artifacts
      if: inputs.action == 'download' || inputs.action == 'download-all'
      shell: bash
      run: |
        echo "Downloaded artifacts:"
        find ${{ inputs.path || inputs.name || 'artifacts/' }} -type f -exec ls -la {} \; || echo "No artifacts found"

    - name: Handle artifact errors
      if: failure() && inputs.fail-on-error == 'false'
      shell: bash
      run: |
        echo "Artifact operation failed but continuing due to fail-on-error=false"
        exit 0
