name: Test Scoop Formula

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Formula
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Scoop
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        shell: powershell

      - name: Validate and install
        run: |
          # Validate JSON syntax
          $manifest = Get-Content "bucket\rxiv-maker.json" | ConvertFrom-Json
          Write-Host "✅ JSON syntax valid"

          # Install from local manifest
          scoop install "${{ github.workspace }}\bucket\rxiv-maker.json"

          # Test it works
          rxiv --version
          rxiv --help

          Write-Host "✅ Installation and basic functionality test passed"
        shell: powershell
